// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNj6AUwCik7zx83g5CmNiurG1t27Uzo6E',
    appId: '1:327892676518:web:48bb2fe5529b2f7fe4a967',
    messagingSenderId: '327892676518',
    projectId: 'artbyhager',
    authDomain: 'artbyhager.firebaseapp.com',
    storageBucket: 'artbyhager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmKscXJMF-C5lGTquBn5cOYgwFJ3tjjjQ',
    appId: '1:327892676518:android:942ee21194cf6a7ce4a967',
    messagingSenderId: '327892676518',
    projectId: 'artbyhager',
    storageBucket: 'artbyhager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIHGJGvyB3EKMQW7nQ2GNeFa_JCI0xBOc',
    appId: '1:327892676518:ios:3c49434183c98f2ae4a967',
    messagingSenderId: '327892676518',
    projectId: 'artbyhager',
    storageBucket: 'artbyhager.firebasestorage.app',
    iosBundleId: 'com.example.artByHagerIsmail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIHGJGvyB3EKMQW7nQ2GNeFa_JCI0xBOc',
    appId: '1:327892676518:ios:3c49434183c98f2ae4a967',
    messagingSenderId: '327892676518',
    projectId: 'artbyhager',
    storageBucket: 'artbyhager.firebasestorage.app',
    iosBundleId: 'com.example.artByHagerIsmail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNj6AUwCik7zx83g5CmNiurG1t27Uzo6E',
    appId: '1:327892676518:web:48bb2fe5529b2f7fe4a967',
    messagingSenderId: '327892676518',
    projectId: 'artbyhager',
    authDomain: 'artbyhager.firebaseapp.com',
    storageBucket: 'artbyhager.firebasestorage.app',
  );
}
